name = "local_registry"
uuid = "df54288b-a541-4846-bdce-e9842cb2b929"
repo = "/home/romeo/.julia/registries/local_registry"

[packages]
131bfee0-d7fc-448d-a615-6b626323d8ce = { name = "RunwayLib", path = "R/RunwayLib" }
2b83b5e6-75ac-4935-a092-400fa6ce651e = { name = "AA228V_FinalProject", path = "A/AA228V_FinalProject" }
4a50f2c7-854b-4ecf-96c4-63ef3198682d = { name = "DictionaryDistance", path = "D/DictionaryDistance" }
778123d0-3295-4563-8004-fb5c576fbcd9 = { name = "KSVD", path = "K/KSVD" }
97992f1d-b083-46ab-ad9c-863c50d80d12 = { name = "DensityIntegrator", path = "D/DensityIntegrator" }
987ad435-e993-44fa-9c05-fce934ed82f8 = { name = "GeodesyXYZExt", path = "G/GeodesyXYZExt" }
9f9888c4-b286-4126-9f88-fdfc7f7e7d1b = { name = "RunwayPNPSolve", path = "R/RunwayPNPSolve" }
bbc1677d-7cf1-46ff-9fcf-9af1de965559 = { name = "MvNormalCalibration", path = "M/MvNormalCalibration" }
