name = "local_registry"
uuid = "df54288b-a541-4846-bdce-e9842cb2b929"
repo = "git@github.com:RomeoV/local_registry.git"

[packages]
131bfee0-d7fc-448d-a615-6b626323d8ce = { name = "RunwayLib", path = "R/RunwayLib" }
4a50f2c7-854b-4ecf-96c4-63ef3198682d = { name = "DictionaryDistance", path = "D/DictionaryDistance" }
987ad435-e993-44fa-9c05-fce934ed82f8 = { name = "GeodesyXYZExt", path = "G/GeodesyXYZExt" }
9f9888c4-b286-4126-9f88-fdfc7f7e7d1b = { name = "RunwayPNPSolve", path = "R/RunwayPNPSolve" }
